// Place your settings in this file to overwrite the default settings
{
  "editor.fontFamily": "Fira Code, Menlo, monospace",
  "editor.fontLigatures": true,
  "editor.tabSize": 2,
  "editor.formatOnSave": true,
  "workbench.editor.showTabs": false,
  "window.restoreFullscreen": true,
  "terminal.external.osxExec": "Hyper.app",
  "workbench.colorTheme": "One Dark Pro",
  "workbench.iconTheme": "material-icon-theme",
  "workbench.colorCustomizations": {
    "terminal.foreground": "#eff0eb",
    "terminal.ansiBlack": "#282a36",
    "terminal.ansiRed": "#ff5c57",
    "terminal.ansiGreen": "#5af78e",
    "terminal.ansiYellow": "#f3f99d",
    "terminal.ansiBlue": "#57c7ff",
    "terminal.ansiMagenta": "#ff6ac1",
    "terminal.ansiCyan": "#9aedfe",
    "terminal.ansiWhite": "#f1f1f0",
    "terminal.ansiBrightBlack": "#686868",
    "terminal.ansiBrightRed": "#ff5c57",
    "terminal.ansiBrightGreen": "#5af78e",
    "terminal.ansiBrightYellow": "#f3f99d",
    "terminal.ansiBrightBlue": "#57c7ff",
    "terminal.ansiBrightMagenta": "#ff6ac1",
    "terminal.ansiBrightCyan": "#9aedfe",
    "terminal.ansiBrightWhite": "#eff0eb"
  },
  "editor.minimap.enabled": true,
  "git.confirmSync": false,
  "files.associations": {
    ".env": "ini",
    ".env.example": "ini",
    ".buckconfig": "ini",
    ".flowconfig": "ini",
    ".gitignore": "ini",
    ".gitattributes": "ini",
    ".gitmodules": "ini",
    ".eslintignore": "ini",
    ".htaccess": "ini",
    "*.sln": "ini",
    ".prettierrc": "json",
    ".sequelizerc": "javascript"
  },
  "csharp.suppressDotnetInstallWarning": true,
  "files.exclude": {
    "**/.github": true,
    "**/.travis.yml": true,
    "**/.gitattributes": true,
    "**/.gitkeep": true,
    "**/composer.lock": true,
    "**/dist": false,
    "**/cache": true,
    "**/node_modules": true,
    "**/bower_components": true,
    "**/vendor": true,
    "**/uploads": true,
    "**/languages": true,
    "**/upgrade": true,
    "**/LICENSE.md": true,
    "**/license.txt": true,
    "**/readme.html": true,
    "**/CHANGELOG.md": true,
    "**/.sass-cache": true,
    "**/storage": true,
    "**/artisan": true,
    "**/phpspec.yml": true,
    "**/phpunit.xml": true,
    "**/yarn.lock": true,
    "**/server.php": true,
    "**/wp-admin": true,
    "**/wp-includes": true,
    "**/wp-activate.php": true,
    "**/wp-blog-header.php": true,
    "**/wp-comments-post.php": true,
    "**/wp-cron.php": true,
    "**/wp-links-opml.php": true,
    "**/wp-load.php": true,
    "**/wp-login.php": true,
    "**/wp-mail.php": true,
    "**/wp-settings.php": true,
    "**/wp-signup.php": true,
    "**/wp-trackback.php": true,
    "**/xmlrpc.php": true,
    "**/.nyc_output": true,
    "**/coverage": true,
    "**/.idea": true,
    "bootstrap/": true,
    "ios/": true,
    "android/": true,
    ".collabignore": true,
    "Builds/": true,
    "**/.tmp": true,
    "**/.ase": true
  },
  "workbench.sideBar.location": "left",
  "workbench.startupEditor": "newUntitledFile",
  "emmet.syntaxProfiles": {
    "php": "html",
    "html": "html",
    "laravel-blade": "html"
  },
  "window.zoomLevel": 0,
  "material-icon-theme.activeIconPack": "react_redux",
  "material-icon-theme.hidesExplorerArrows": false,
  "cSpell.userWords": [
    "airbnb",
    "airbnb's",
    "autoprefixed",
    "backend",
    "bulma",
    "component",
    "datetime",
    "devtool",
    "dropdown",
    "ellipsize",
    "endforeach",
    "ethereum",
    "favicons",
    "favourite",
    "formik",
    "fullheight",
    "hoverable",
    "initialise",
    "keyframes",
    "laravel",
    "lodash",
    "microservice",
    "mimetype",
    "noopener",
    "noreferrer",
    "organisation",
    "permalink",
    "plugin",
    "postdata",
    "reset",
    "strapline",
    "styleguide",
    "synchronise",
    "toarray",
    "typeform",
    "unassign",
    "unmount",
    "valign",
    "walkthrough",
    "webp",
    "webpack",
    "whistleblowing",
    "will",
    "woff",
    "wp"
  ],
  "git.autofetch": true,
  "explorer.confirmDragAndDrop": false,
  "prettier.singleQuote": true,
  "prettier.trailingComma": "all",
  "prettier.arrowParens": "always",
  "prettier.bracketSpacing": true
}
