#!/bin/bash
# Create a .htaccess to fetch Wordpress uploads from a live site

echo "<IfModule mod_rewrite.c>
  RewriteEngine On
  RewriteBase /wp-content/uploads/
  RewriteCond %{REQUEST_FILENAME} !-f
  RewriteCond %{REQUEST_FILENAME} !-d
  RewriteRule ^(.*) ${1}wp-content/uploads/\$1 [L,P]
</IfModule>" > ./wp-content/uploads/.htaccess
echo "Created .htaccess file for Wordpress uploads on '${1}wp-content/uploads/'"
